### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by Tlntin** [hanxixuana/flowrisk#1]
Traceback (most recent call last):
  File "E:/PycharmProjects/api爬虫/vpin-master2/vpin-bvc.py", line 1, in <module>
    import flowrisk as fr
  File "D:\Program Files (x86)\python38\lib\site-packages\flowrisk\__init__.py", line 11, in <module>
    import measure
  File "D:\Program Files (x86)\python38\lib\site-packages\measure\__init__.py", line 5, in <module>
    from .stats import (
  File "D:\Program Files (x86)\python38\lib\site-packages\measure\stats\__init__.py", line 8, in <module>
    from .counter import (
  File "D:\Program Files (x86)\python38\lib\site-packages\measure\stats\counter.py", line 5, in <module>
    from .stat import (
  File "D:\Program Files (x86)\python38\lib\site-packages\measure\stats\stat.py", line 9, in <module>
    from measure.client.base import BaseClient
  File "D:\Program Files (x86)\python38\lib\site-packages\measure\client\__init__.py", line 11, in <module>
    for name, client in globals().items():
RuntimeError: dictionary changed size during iteration

**Comment by Tlntin** [comment]
when I import with "import flowrisk as fr" ,is error

**Comment by hanxixuana** [comment]
hi man r u using 3.*?

if yes, please try this one https://github.com/foonsun/flowrisk

**Comment by Tlntin** [comment]
ok,I solve it.Thank you.

**Comment by hanxixuana** [comment]
i also updated it to support 3.8
